#!/bin/bash

rm -rf covrep/*

lcov --rc lcov_branch_coverage=1 -c -b . -d ../build/gcov/ > tests_coverage.info
lcov -r tests_coverage.info '/usr/include*' '*/gtest/g*' > clean_ut_coverage.info
genhtml --rc genhtml_branch_coverage=1 clean_ut_coverage.info -o covrep/ --branch-coverage -f
rm tests_coverage.info